### ISSUE TITLE
Cosas Deployment ERATOSTHENES

### ISSUE THREAD

**Issue by JesusGarciaRodriguez** [nataliaborgonos/Server_PDP_PEP#1]
-	El Readme habrá que rellenarlo poco a poco, le he dado estructura como los tenemos otros.
-	Hay que crear docker-compose.yml para lanzar esto. Aunque solo tengamos un único componente así somos consistentes con el resto. Si te fijas he puesto en el Readme que tendremos uno para que haga build de la imagen y otro para que use la que tenemos en el repositorio privado, esto es parecido a como lo tenemos en otros repositorios (por ejemplo te puedes fijar en como están los docker-compose.yml en https://ci-cysec.eng.it/gitlab/ERATOSTHENES/wp4/ctisa/-/tree/optimize-images?ref_type=heads, y el Dockerfile: https://ci-cysec.eng.it/gitlab/ERATOSTHENES/wp4/ctisa/-/blob/optimize-images/Connector/connector.Dockerfile?ref_type=heads)
o	Las cosas configurables, con variables de entorno como se hace en estos (se ponen en el .env y en el docker-compose se leen de ahí).

**Comment by JesusGarciaRodriguez** [comment]
Dependencia #2

**Comment by nataliaborgonos** [comment]
No sé muy bien cómo poner lo del docker-compose para que haga un build de la imagen. Ahora mismo lo hago con docker-compose build

**Comment by JesusGarciaRodriguez** [comment]
La idea sería hacer:
- Un fichero docker-compose-build.yml como en https://ci-cysec.eng.it/gitlab/ERATOSTHENES/wp4/ctisa/-/blob/optimize-images/docker-compose-full.yml?ref_type=heads, que lleva para el contenedor (aparte de variables de entorno y demás) que lleva un campo build: que indica el Dockerfile y un campo image que en este caso indica el TAG de la imagen que sea crea al hacer docker-compose -f docker-compose-build.yml build
- Un fichero docker-compose.yml como en https://ci-cysec.eng.it/gitlab/ERATOSTHENES/wp4/ctisa/-/blob/optimize-images/docker-compose.yml que lleva para el contenedro solo el campo image (sin build), de forma que sirve para hacer docker-compose up/pull y lo que hace es traerse la imagen del repositorio del proyecto (se trae en concreto el TAG que se indica en el campo image)

**Comment by JesusGarciaRodriguez** [comment]
Además, el Dockerfile lo suyo sería cambiarlo para que el build del PDP-PEP internamente, sin tener que el build con gradle en el host. 
Idealmente sería con un Dockerfile como este: https://ci-cysec.eng.it/gitlab/ERATOSTHENES/wp4/ctisa/-/blob/optimize-images/Connector/connector.Dockerfile, que hace "multi-stage", en el primer paso se haría el build del PDP-PEP, el segundo paso sería como el que hay ahora en el Dockerfile que coge el jar ya creado y lo prepara para ejecutarlo.

**Comment by nataliaborgonos** [comment]
Tengo todo esto casi hecho, lo único, para el tema del testing, pongo un comando dentro del Dockerfile para que se ejecuten automáticamente o dejo un comando para que se ejecuten manualmente?

**Comment by JesusGarciaRodriguez** [comment]
Para testing basta con que se puedan ejecutar manualmente. Para los unitarios directamente testing y para los de integración pues lanzando las dependencias antes de lanzar el test completo (todo esto explicado en el Readme, que cre oque ya estaba más menos).

**Comment by nataliaborgonos** [comment]
De acuerdo. En el readme pone algo de Nexus Repository, hay que subir la imagen a algún sitio ?

**Comment by JesusGarciaRodriguez** [comment]
Sí, cuando esté la imagen funcionando y testeada, hay que subirla al repositorio de imágenes del proyecto. Habrá que ir creando TAGs según se vayan haciendo cambios y demás. Eso lo podemos ver un día.

**Comment by nataliaborgonos** [comment]
Perfecto. Ahora mismo está prácticamente todo, quizás podría hacer un script para lanzar los tests en vez de poner el comando como tal. Esta tarde voy a seguir redactando el readme
