### ISSUE TITLE
Configurable

### ISSUE THREAD

**Issue by JesusGarciaRodriguez** [nataliaborgonos/Server_PDP_PEP#2]
-	Hay que hacer configurables las cosas que hace falta para lanzar el componente y que funcione bien y demás.  Idealmente como variables de entorno
- Algunos ejemplos que seguro que se pasa alguno: Los certificados de claves (públicas/privadas), la IP/puerto para integrar con DLT, usar la versión PDP/PEP de ERATOSTHENES o una de “test/mock”, el puerto de escucha del PDP/PEP en sí, IP/puerto del Agente de identidad…

**Comment by nataliaborgonos** [comment]
De momento he añadido estas variables de entorno para hacer configurables las siguientes cosas:
PDP_PORT=8088 (puerto donde escucha el server)
PDP_CONFIG=erathostenes (politicas y trustscore)
PDP_KS=/app/crypto/serverErat.ks (keystore del server)
PDP_PW=hola123 (password del keystore)
PDP_ALIAS=MiAliasPriv 
DLT_IP=localhost (ip donde escucha el cliente grpc del dlt)
DLT_PORT=8080 (puerto donde escucha el cliente grpc del dlt)
IDAGENT_KS=/app/crypto/ec-cakey.jks (keystore del agente de aries)
IDAGENT_PW=hola123
IDAGENT_ALIAS=myserver
IDAGENT_CERT=/app/crypto/ec-cacert.pem (certificado del agente de aries)
